### ISSUE TITLE
能不能传同一个uniquename分别到gpt和claude

### ISSUE THREAD

**Issue by ixxmu** [nianhua99/PandoraHelper#101]
如果我有一个用户user001，添加了2个服务，gpt和claude， 但是设置为一个unique name，登陆之后让用户自己选使用claude还是gpt；对于只有一个服务的用户，登陆后直接跳转到对应的gpt或者claude即可！ 不然的话一个人共享需要记住两套用户名和密码。

另，能否限制登录设备，比如一个用户同时只能登录到一个设备上。

感谢佬这么棒的迭代！

**Comment by nianhua99** [comment]
这个也许不行，unique name在系统内需要是唯一的，主要是需要通过unique name定位到账号，如果有多个重复的Unique name的话，就会命中多个账号，就乱套了，总不能让用户选择哪个账号

**Comment by nianhua99** [comment]
限制登录设备应该也做不了，也许可以记录ip数量

**Comment by hnuzhoulin** [comment]
将unique name和用户名区分开，另外用户名登陆后可以选择该用户下所有的gpt和claude
，可以自己选择去哪一个，再跳到始皇对应的网站，目前输入用户名密码是自动跳到账号对应的gpt或者claude，登陆界面还在。

**Comment by nianhua99** [comment]
> 将unique name和用户名区分开，另外用户名登陆后可以选择该用户下所有的gpt和claude ，可以自己选择去哪一个，再跳到始皇对应的网站，目前输入用户名密码是自动跳到账号对应的gpt或者claude，登陆界面还在。

登录后原来的页面还在，这个是故意的，因为helper本身独立于oaifree/fuclaude
