### ISSUE TITLE
/admin管理页面报错404

### ISSUE THREAD

**Issue by dabai1109** [nianhua99/PandoraHelper#106]
**version：1.2.0**

**使用 ip:9000/admin 访问管理页面报错404**

以下是报错信息：
Unexpected Application Error!
404 Not Found

**查看服务器上的日志，没有错误信息，前端控制台也没有报错**

**ip:9000/login 该路径是可以正常访问的**

**Comment by nianhua99** [comment]
已修复，登录跳转的路径写错了，更新1.2.1即可使用
