### ISSUE TITLE
FreeBSD 启动报错：sonyflake not created

### ISSUE THREAD

**Issue by OnceNever** [nianhua99/PandoraHelper#113]
### 软件版本
PandoraHelper-v1.2.2-freebsd-amd64

### 操作系统版本
14.1-RELEASE-p3 FreeBSD   serv00小鸡

### 操作步骤
- 解压
- config文件配置后台密码
- ./PandoraHelper 启动

### 错误日志
`load conf file: data/
panic: sonyflake not created

goroutine 1 [running]:
PandoraHelper/pkg/sid.NewSid(...)
        PandoraHelper/pkg/sid/sid.go:14
PandoraHelper/cmd/server/wire.NewWire(0x8705001c0, 0x8705200b8)
        PandoraHelper/cmd/server/wire/wire_gen.go:31 +0x86c
main.main()
        ./main.go:37 +0xe5`

**Comment by nianhua99** [comment]
换台机器，有些机器的网络有问题，比如IPV4 IPV6，会导致无法创建sonyflake

**Comment by maggch97** [comment]
> 换台机器，有些机器的网络有问题，比如IPV4 IPV6，会导致无法创建sonyflake

我搜了一下，机器没有内网ip会有这个问题。
sonyflake本身是为了分布式设计的，如果是单机的话直接用uuid是不是也足够了

**Comment by nianhua99** [comment]
> > 换台机器，有些机器的网络有问题，比如IPV4 IPV6，会导致无法创建sonyflake
> 
> 我搜了一下，机器没有内网ip会有这个问题。 sonyflake本身是为了分布式设计的，如果是单机的话直接用uuid是不是也足够了

是这个原因，Helper后端用的是go-nunu这个框架，框架自带了这个，我可以去掉它

**Comment by Stardustll** [comment]
> > > 换台机器，有些机器的网络有问题，比如IPV4 IPV6，会导致无法创建sonyflake
> > 
> > 
> > 我搜了一下，机器没有内网ip会有这个问题。 sonyflake本身是为了分布式设计的，如果是单机的话直接用uuid是不是也足够了
> 
> 是这个原因，Helper后端用的是go-nunu这个框架，框架自带了这个，我可以去掉它

请问除了换机器，怎么解决这个问题？
