### ISSUE TITLE
ARM 版本添加账户时错误

### ISSUE THREAD

**Issue by Sleepstars** [nianhua99/PandoraHelper#114]
尝试过 latest 与 1.3.0的镜像均有相同问题，添加chatgpt共享列表时，有如下报错：
“eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJzZXNzaW9uX2lkIjoicEtodmp5bHJXcFZQaGE0RHlkQUg3ZXNHVHZCajI3VEYiLCJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJkbTduYWpreUBkdWNrLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS9hdXRoIjp7InBvaWQiOiJvcmctSWNaOHRTYWd5OXRscWJ2NmJmMHVTOFcyIiwidXNlcl9pZCI6InVzZXItcklqR21HVFhLTm93dURHOHNXTnR1WDNhIn0sImlzcyI6Imh0dHBzOi8vYXV0aDAub3BlbmFpLmNvbS8iLCJzdWIiOiJhdXRoMHw2NTJlMTNiZTcxYTBiZTcwOGQ1Y2JkMDgiLCJhdWQiOlsiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MSIsImh0
相同配置环境下则无该问题

**Comment by nianhua99** [comment]
尽快删掉这个ISSUE，你把你token贴出来干啥，另外可以把完整的报错日志私聊给我

**Comment by Sleepstars** [comment]
感谢感谢，刚刚剪切板窜行了没发现！！！
（另似乎issue只能由owner删除）
