### ISSUE TITLE
开启一键反代后，对话报错或收不到流式恢复，需要刷新才会显示回答

### ISSUE THREAD

**Issue by ZackYJz** [nianhua99/PandoraHelper#118]
<img width="1113" alt="CleanShot 2024-09-21 at 13 22 43@2x" src="https://github.com/user-attachments/assets/9f0ca917-aabc-4a72-8f2e-ea0a47f2adbf">

刷新页面后：

<img width="1068" alt="CleanShot 2024-09-21 at 13 25 06@2x" src="https://github.com/user-attachments/assets/6fe6812d-2cb7-471a-a6e6-7971e6007851">

**Comment by panthole** [comment]
+1 貌似claude没问题，只有chatgpt会

**Comment by nianhua99** [comment]
应该是检测对话模型的时候报的错，我晚点修复下

**Comment by nianhua99** [comment]
两个问题已全部修复，更新v1.3.3 @panthole @ZackYJz

**Comment by ZackYJz** [comment]
@nianhua99 在输出长内容回答时会卡主报错，似乎是输出固定的长度的内容后触发：
<img width="1005" alt="CleanShot 2024-09-24 at 10 31 14@2x" src="https://github.com/user-attachments/assets/fa2871c0-8284-4b77-bf58-26a84ca88f0f">
