### ISSUE TITLE
login页面登录时候报错Unexpected end of JSON input

### ISSUE THREAD

**Issue by yi447780897** [nianhua99/PandoraHelper#120]
dockers日志报错：

2024/09/23 03:22:47 [Recovery] 2024/09/23 - 03:22:47 panic recovered:
runtime error: invalid memory address or nil pointer dereference
runtime/panic.go:262 (0x4715f8)
runtime/signal_unix.go:900 (0x4715c8)
PandoraHelper/internal/service/share.go:162 (0xe9b407)
PandoraHelper/internal/handler/share.go:36 (0xe9fcc1)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x99478a)
PandoraHelper/internal/middleware/log.go:32 (0xf793f6)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x99478a)
PandoraHelper/internal/middleware/log.go:40 (0xf794fa)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x99478a)
PandoraHelper/internal/middleware/cors.go:21 (0xf7e3b7)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xf5950d)
github.com/ulule/limiter/v3@v3.11.2/drivers/middleware/gin/middleware.go:64 (0xf5949c)
github.com/ulule/limiter/v3@v3.11.2/drivers/middleware/gin/middleware.go:35 (0xf592fc)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x9a14ce)
github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x9a14bb)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x9a061c)
github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x9a0603)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x99fb0d)
github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x99f7a4)
github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x99f2f1)
net/http/server.go:3210 (0x74b64d)
net/http/server.go:2092 (0x72ac4f)
runtime/asm_amd64.s:1700 (0x4774c0)

**Comment by yi447780897** [comment]
配置文件使用的是/data/config 只修改了管理员密码，其他文件没有变动

**Comment by nianhua99** [comment]
配置文件发一下我看看

**Comment by nianhua99** [comment]
你创建share用户了吗

**Comment by yi447780897** [comment]
{
  "security": {
    "admin_password": "123"
  },
  "http": {
    "host": "0.0.0.0",
    "port": 9000,
    "proxy-pass": {
      "oaifree": {
        "enable": true,
        "host": "https://new.oaifree.com",
        "port": 9001
      },
      "fuclaude": {
        "enable": true,
        "host": "https://demo.fuclaude.com",
        "port": 9002
      }
    },
    "title": "Pandora",
    "rate": 1000
  },
  "database": {
    "driver": "sqlite",
    "dsn": "./data/data.db"
  },
  "share": {
    "random": true,
    "custom": true
  },
  "pandora": {
    "domain": {
      "chat": "https://chat.oaifree.com",
      "token": "https://token.oaifree.com",
      "index": "https://new.oaifree.com",
      "claude": "https://demo.fuclaude.com"
    }
  },
  "moderation": {
    "apiKey": "",
    "apiUrl": "https://api-proxy.oaipro.com/v1/moderations",
    "message": "您的消息包含不当内容，请修改后重试!"
  },
  "oneapi": {
    "token": "",
    "domain": ""
  },
  "log": {
    "level": "info",
    "encoding": "console",
    "output": "console",
    "log_file_name": "./logs/server.log",
    "max_backups": 30,
    "max_age": 7,
    "max_size": 1024,
    "compress": true
  }
}

**Comment by yi447780897** [comment]
![image](https://github.com/user-attachments/assets/3ed272ac-d90d-4dd2-8b69-a39382880b38)

**Comment by yi447780897** [comment]
上面是我的配置和创建共享账户，帮忙看下有问题吗？

**Comment by nianhua99** [comment]
> 上面是我的配置和创建共享账户，帮忙看下有问题吗？

这个不是共享账户，这是你的原始ChatGPT账号，你可以点击【共享】列的 【+】 号创建一个共享用户，创建的时候会让你输入Unique Name和Password，在首页用这个Uniquename和Password登录就可以了

**Comment by yi447780897** [comment]
可以了，谢谢大佬

**Comment by yi447780897** [comment]
？
refresh token，除了论坛有其他方式获取吗

**Comment by nianhua99** [comment]
论坛里有帖子说怎么自己获取的，但是我没试过

**Comment by yi447780897** [comment]
好吧，我没有论坛账号，很难搞，现在还不能注册
