### ISSUE TITLE
在账号列表点击共享按钮之后显示报错字段映射不到

### ISSUE THREAD

**Issue by wwq0702** [nianhua99/PandoraHelper#121]
![image](https://github.com/user-attachments/assets/db7fe131-7597-4152-a328-1b32d4be48f3)
![image](https://github.com/user-attachments/assets/7ccc3b09-f50f-43f9-a382-b2006463b859)
在账号列表点击共享按钮之后显示报错字段映射不到
mysql数据库

**Comment by nianhua99** [comment]
看下后端有日志不

**Comment by wwq0702** [comment]
<img width="2432" alt="image" src="https://github.com/user-attachments/assets/080131ab-adda-469c-82cd-3bdc121a14e9">有个500 但是不是很详细

**Comment by wwq0702** [comment]
<img width="1863" alt="image" src="https://github.com/user-attachments/assets/f53b384c-853a-4bf4-b803-c333d2d14e5b">
数据库share表也是正常的 拿到share token也可以正常访问页面 就是这个share列表无法访问报错这个信息
还有一个信息是我是用的mysql 会跟这个有关系吗

**Comment by wwq0702** [comment]
<img width="990" alt="image" src="https://github.com/user-attachments/assets/0bb29047-62b4-4498-a948-47f22d32190f">
这是配置文件。大佬麻烦您了

**Comment by nianhua99** [comment]
已修复，你可以更新v1.3.3
