### ISSUE TITLE
@nianhua99 在输出长内容回答时会卡主并报错

### ISSUE THREAD

**Issue by ZackYJz** [nianhua99/PandoraHelper#122]
@nianhua99 在输出长内容回答时会卡主并报错，似乎是输出固定的长度的内容后触发：
<img width="1005" alt="CleanShot 2024-09-24 at 10 31 14@2x" src="https://github.com/user-attachments/assets/fa2871c0-8284-4b77-bf58-26a84ca88f0f">

_Originally posted by @ZackYJz in https://github.com/nianhua99/PandoraHelper/issues/118#issuecomment-2369988634_

**Comment by nianhua99** [comment]
只有长内容会这样吗

**Comment by ZackYJz** [comment]
> 只有长内容会这样吗

目前观察是这样的，输出大段代码时会卡在一个相似的位置。然后抛出这个异常，随后刷新页面，也能看到完整的返回结果

**Comment by nianhua99** [comment]
已修复，请更新v1.3.4
