### ISSUE TITLE
ubuntu docker 起的服务进不去

### ISSUE THREAD

**Issue by yaxAltman9** [nianhua99/PandoraHelper#123]
配置文件修改了端口和日志等级“debug”，docer-compose只修改端口号，看docker的日志都是成功，但是日志等级还是显示info-使用公网ip+修改后端口访问

使用docker-desktop（win）使用正常-使用localhost访问

**Comment by nianhua99** [comment]
看一下本地的那个端口开放没，还有安全组之类的排查下
