### ISSUE TITLE
docker 设置时区不成功，希望延长 RT 转 AT 之间的时间间隔

### ISSUE THREAD

**Issue by sunkoto** [nianhua99/PandoraHelper#128]
1、docker 设置时区 TZ Asia/Shanghai 不成功，实际还是+0000时区，环境 unraid 6.12.6 ,docker 20.10.24 ;
2、鉴于目前风控拉高，建议可以自定义 RT 转 AT 之间的时间间隔，比如7-10天，而不是默认每天都生成新的 AT。

感谢年华佬友(๑•́₃•̀๑)

**Comment by nianhua99** [comment]
时区这个问题我看下
第二个这个，RT转AT应该不会触发风控

**Comment by SY666888** [comment]
同样的建议可以自定义 RT 转 AT 之间的时间间隔，比如7-10天，而不是默认每天都生成新的 AT。号最近总是被要求重置密码。

**Comment by jipiyan** [comment]
同样的建议可以自定义 RT 转 AT 之间的时间间隔，比如7天，最近多次被要求重置密码。

**Comment by nianhua99** [comment]
第二个问题已修复，请更新v1.3.4，第一个我再看下

**Comment by sunkoto** [comment]
> 第二个问题已修复，请更新v1.3.4，第一个我再看下

<img width="405" alt="image" src="https://github.com/user-attachments/assets/2216ebbe-4f34-44df-bde0-27ce0c4afd01">
是在这里加一个  "account_refresh_cron": ""   对吧？
时区还没修呢就给 Close 了！
“尽快修复！” ——NEO
