### ISSUE TITLE
main分支好像不是最新的代码？

### ISSUE THREAD

**Issue by Jazzylol** [nianhua99/PandoraHelper#130]
v1.3x代码不合回main吗

**Comment by Jazzylol** [comment]
想提PR

**Comment by nianhua99** [comment]
代码应该是最新的呀

**Comment by nianhua99** [comment]
> 想提PR

可以的，哪个issue的pr？

**Comment by Jazzylol** [comment]
> 代码应该是最新的呀

我看main分支并没有内部反代的代码，代码在v1.3x上

**Comment by Jazzylol** [comment]
> > 想提PR
> 
> 可以的，哪个issue的pr？

需求1：自定义分享路径   /share可以是默认的分享路径，但是一个账号选择有一个或者多个分享路径 比如 /a /b /c  表示这个账号会出现在   xx.com/a   xx.com/b xx.com/c 上面，这个需求的背景就是我需要对不同的群里分享不同的账号，而不是大家都用 /share这个页面

需求2：每个分享页面一些基本信息可以自定义，比如 文字，公告 之类的，当然这个我也可以硬编码 自己改自己打包

需求3:  分享页面需要一些账号的额外信息，比如当前可用账号总数，比如一个账号最近5分钟有聊天记录，显示xx颜色，超过多少条显示繁忙之类的（这个基于 conversation表去做) 

可以讨论下 这几个需求是否合理

**Comment by nianhua99** [comment]
> > > 想提PR
> > 
> > 
> > 可以的，哪个issue的pr？
> 
> 需求1：自定义分享路径 /share可以是默认的分享路径，但是一个账号选择有一个或者多个分享路径 比如 /a /b /c 表示这个账号会出现在 xx.com/a xx.com/b xx.com/c 上面，这个需求的背景就是我需要对不同的群里分享不同的账号，而不是大家都用 /share这个页面
> 
> 需求2：每个分享页面一些基本信息可以自定义，比如 文字，公告 之类的，当然这个我也可以硬编码 自己改自己打包
> 
> 需求3: 分享页面需要一些账号的额外信息，比如当前可用账号总数，比如一个账号最近5分钟有聊天记录，显示xx颜色，超过多少条显示繁忙之类的（这个基于 conversation表去做)
> 
> issue: 聊天初始化界面中，点击openai的图标 可以跳转到voice.oaifree.com 这个好像是没有在反代的配置项里的
> 
> 可以讨论下 这几个需求是否合理

这些都是需求，可以单独提issue，如果你会实现的话可以提PR。
第二个和第三个是可以有的，第一个比较定制了
