### ISSUE TITLE
共享用户有权限能够删除聊天记录和注销账户！大佬能添加限制吗？

### ISSUE THREAD

**Issue by yulongwanxue** [nianhua99/PandoraHelper#131]
![清除记录](https://github.com/user-attachments/assets/485f88a7-02de-4be7-9549-b9ff4b1c68d9)
![删除账户](https://github.com/user-attachments/assets/d3566170-1084-4007-acc2-be90451409cf)

**Comment by nianhua99** [comment]
这接口对分享用户已经被屏蔽了，点了也没用。
你只需要注意AccessToken不要泄露即可
