### ISSUE TITLE
登录后跳转

### ISSUE THREAD

**Issue by King-Wanghai** [nianhua99/PandoraHelper#132]
/login登录后会跳转到新的页签，可以改成登录成功后在当前页签跳转吗？

**Comment by nianhua99** [comment]
这个可以自行二开修改一下

**Comment by King-Wanghai** [comment]
fork之后，修改了代码，构建时报错呢，还有如何生成docker并上传到hub中？希望大佬能够指点一下
![QQ20241014-131635](https://github.com/user-attachments/assets/5d183fb0-ddde-46e4-81b6-cf03569a6f48)
