### ISSUE TITLE
更好地分享fk

### ISSUE THREAD

**Issue by bccwuho** [nianhua99/PandoraHelper#140]
在共享列表的操作列中，点击“登录并跳转至对话”是不是相当于调用“https://new.oaifree.com/auth/login_share?token=fk-。。。”？
是的话，能不能单独提供一列方便地取到fk，以便更好地用这个URL来分享，因为有时这样比账号/密码更方便。

**Comment by nianhua99** [comment]
共享列表右上角有个开关，简略/详细 模式切换可以看到fk

**Comment by bccwuho** [comment]
看到了，这个赞！谢谢！
