### ISSUE TITLE
Claude 对话隔离支持

### ISSUE THREAD

**Issue by Lorde627** [nianhua99/PandoraHelper#144]
Fuclaude 已经支持会话隔离，想问一下 PandoraHelper 后续会跟进吗？👀

> 需要通过 oauth 登录实现。生成 oauth_token 时指定 unique_name 参数。跟 oaifree 的 ShareToken 差不多。unique_name 不传则不隔离。

```
curl 'http://127.0.0.1:8181/manage-api/auth/oauth_token' \
-H 'Content-Type: application/json' \
-d '{
    "session_key": "sk-ant-sid01-xxx",
    "unique_name": "test"
}'
```

**Comment by nianhua99** [comment]
现在就是支持的把

**Comment by Lorde627** [comment]
在 Claude 账号页面没有看到相关的选项，难道是默认开启？
在尝试添加共享账号后，登陆账号后跳转 Fuclaude 会需要输入邮箱和 Session Key 我在想是不是下面的原因导致的：

```
2024-11-19 12:54:35.136 error   PandoraHelper/internal/server/http.go:168       403 访问URL被拦截   {"url": "https://demo.fuclaude.com", "status": 403}
```

**Comment by nianhua99** [comment]
claude账号页面 ，需要用session key 创建一个claude账号，然后点击 分享列的 加号，就可以创建一个share用户，这时会要求输入unique name和password ，这个就是用来对话隔离的。

被拦截的话，说明访问fuclaude不通，可以在前面加一层代理，，修改配置文件中的 pandora.domain.claude 的值

**Comment by Lorde627** [comment]
试了两台服务器加反代都不行 😢
想问一下 Pandora Car 有加上 Claude 的计划吗 👀

**Comment by nianhua99** [comment]
pandora car要后续才会支持了，目前精力不够
