### ISSUE TITLE
新版docker镜像是不是没有更新

### ISSUE THREAD

**Issue by xixi-furry** [nianhua99/PandoraHelper#153]
看dockerhub那边镜像还是在2个月之前。大佬要不要考虑换到github来？

**Comment by nianhua99** [comment]
已推送最新镜像

**Comment by xixi-furry** [comment]
docker 镜像是不是有点问题，提示 docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/app/PandoraHelper": permission denied: unknown.

run --rm -it 进去过后发现没有执行权限，手动chmod后正常。

**Comment by nianhua99** [comment]
> docker 镜像是不是有点问题，提示 docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/app/PandoraHelper": permission denied: unknown.
> 
> run --rm -it 进去过后发现没有执行权限，手动chmod后正常。

确实有这个问题！已经重新Push。感谢反馈
