### ISSUE TITLE
refresh失败

### ISSUE THREAD

**Issue by zhuxindong** [nianhua99/PandoraHelper#67]
![image](https://github.com/nianhua99/PandoraHelper/assets/24989246/b2003198-9a49-4932-a476-f264913ee959)
![image](https://github.com/nianhua99/PandoraHelper/assets/24989246/63df90ba-3c96-466b-b34c-28113c3fcd0a)

**Comment by nianhua99** [comment]
没有填Refresh Token

**Comment by zhuxindong** [comment]
> 没有填Refresh Token

不能只填账号密码吗

**Comment by nianhua99** [comment]
> > 没有填Refresh Token
> 
> 不能只填账号密码吗

现在只能通过Refresh Token刷新Access Token，所以如果不填RT是刷新不了的，需要手动更新AccessToken

**Comment by zhuxindong** [comment]
> > > 没有填Refresh Token
> > 
> > 
> > 不能只填账号密码吗
> 
> 现在只能通过Refresh Token刷新Access Token，所以如果不填RT是刷新不了的，需要手动更新AccessToken

那是不是首页的登录功能其实是没用的？

**Comment by nianhua99** [comment]
> > > > 没有填Refresh Token
> > > 
> > > 
> > > 不能只填账号密码吗
> > 
> > 
> > 现在只能通过Refresh Token刷新Access Token，所以如果不填RT是刷新不了的，需要手动更新AccessToken
> 
> 那是不是首页的登录功能其实是没用的？

首页的登录 是用于分享用户的UniqueName+密码登录的
