### ISSUE TITLE
无法隐藏用户email

### ISSUE THREAD

**Issue by VectorZhao** [nianhua99/PandoraHelper#70]
![image](https://github.com/nianhua99/PandoraHelper/assets/16644993/c1625a4e-10f1-4722-a643-92de4aa359e9)
实际测试，用户的邮箱无法隐藏

**Comment by nianhua99** [comment]
这个传参可能有问题

**Comment by duangjiusuang** [comment]
感觉始皇去掉这个参数了，之前写的时候就发现了

**Comment by VectorZhao** [comment]
那就是无论怎么设置都会显示邮箱了

**Comment by nianhua99** [comment]
始皇似乎去掉了这个参数
