### ISSUE TITLE
new-api对接调查

### ISSUE THREAD

**Issue by nianhua99** [nianhua99/PandoraHelper#73]
目前Helper的定位还是方便开ChatGPT共享车，
想知道有多少人需要支持 new-api 对接的？比如
- 将指定的ShareToken同步更新到 new-api
- 在Helper复活PoolToken 将PoolToken同步到new-api

点赞本issue表示你需要此功能，有其他想法可以在下面留言

**Comment by VectorZhao** [comment]
chat2api不是就能传入at吗？传sharetoken也行？

**Comment by yelc66** [comment]
我想需要的,这样是方便很多,

**Comment by Tsenghan** [comment]
chat2api不支持fk直接调用吧，目前还是只支持at
所以把指定的share token对接到new-api没啥用，可以把新刷出来的at通过api自动同步到渠道里边。希望增加这个功能。
