### ISSUE TITLE
【建议】1.0很好用，有个小建议。

### ISSUE THREAD

**Issue by yanwen** [nianhua99/PandoraHelper#75]
期待可以在前台提供一个修改密码的选项。

1.0按照wiki拉起来了，开箱即用，相当不错。

**Comment by nianhua99** [comment]
好提议，应该可以搞一个根据原密码修改新密码的功能，找回密码暂时不做，因为那个需要关联邮箱信息

**Comment by nianhua99** [comment]
已修复
