### ISSUE TITLE
invalid access token

### ISSUE THREAD

**Issue by ShaneLee-Top** [nianhua99/PandoraHelper#76]
大佬，我根据docker compose的教程部署了，可以打开界面。

但是添加账号后，跳转到对话界面时，显示异常，一发消息就提示“invalid access token”。

access token是官网https://chat.openai.com/api/auth/session刚取的，肯定是对的；
界面自带的获取服务也试过了，报错一样的。

看后台日志也没有明显的报错痕迹，想问下有没有什么debug思路呀？

**Comment by nianhua99** [comment]
你的号不是 Plus

**Comment by ShaneLee-Top** [comment]
> 你的号不是 Plus

确实。。
感谢大佬🙏
