### ISSUE TITLE
【Bug】在ios手机上使用账号密码登录不会跳转

### ISSUE THREAD

**Issue by oneCatZz** [nianhua99/PandoraHelper#78]
系统：Ios 17.5
浏览器：Safari
使用账号密码登录似乎是弹窗，在Safari浏览器上默认是开启阻止弹窗的，目前只能用ShareToken登录或者关闭这个设置，希望大佬能优化一下。
![image](https://github.com/nianhua99/PandoraHelper/assets/32626686/2c72c147-5e26-4761-97c8-6368c7ee5f94)

**Comment by nianhua99** [comment]
本来开发的时候，是在当前页面打开的，但是这样会导致用户注销登录后，跳转到没有账号密码框的 oaifree 登录页去，我再想想怎么搞

**Comment by nianhua99** [comment]
已修复
