### ISSUE TITLE
也许是BUG，helper后台的用户使用次数不会更新

### ISSUE THREAD

**Issue by NPC-JIN** [nianhua99/PandoraHelper#84]
我开了五个共享账号，其中一个账号一直保持一个固定的数值：119，到现在持续了大约有两周时间，经我询问，有好几天压根没使用
![image](https://github.com/nianhua99/PandoraHelper/assets/135578279/7a3ec76a-b236-4081-b1cc-25b0f77b9d91)

**Comment by nianhua99** [comment]
目前这个使用次数应该是所有时间加起来的

**Comment by NPC-JIN** [comment]
但是有时候会更新数据，有时候不会啊。很迷
