### ISSUE TITLE
v1.0.2 和v1.0.3 会自动把Access Token 更新为empty

### ISSUE THREAD

**Issue by joekleenubuntu** [nianhua99/PandoraHelper#89]
更新了access token之后，过一段时间就不能用了，去后台一看，access token 被清空了。
![6tUPoXEyrcdnYNl](https://s2.loli.net/2024/06/08/6tUPoXEyrcdnYNl.png)

然后手动添加access token 会出现 500错误。

如图：
![tQEguP7LpnJlmVo](https://s2.loli.net/2024/06/08/tQEguP7LpnJlmVo.png)

**Comment by nianhua99** [comment]
有refresh token的话应该不需要手动加at的，我在排查下

**Comment by joekleenubuntu** [comment]
我仿佛找到了问题的所在，可以复原一下。如果是通过官网获取Refresh Token的话，获取到的Refresh Token会很长 （这个情况隔一段时间Access Token 就会自动更新为empty，而且手动更新 access token会出现500错误）；通过oaifree获取Refresh Token的话，获取到的Refresh Token会很短，用着没问题不会出现500报错，会不会是因为Refresh Token过长或者不兼容oaifree而导致500报错？？

**Comment by NPC-JIN** [comment]
我有遇到过同样的情况，但是我从没有在官网获取过rt（官网不是只有at吗？），出现empty之后，我重新取了一次rt，就一切正常了，感觉是rt过期导致的

**Comment by nianhua99** [comment]
已修复
