### ISSUE TITLE
增加“每个月重置统计的使用量”功能

### ISSUE THREAD

**Issue by hijos** [nianhua99/PandoraHelper#91]
这个重置按钮好像没有用？按了没啥变化。
![image](https://github.com/nianhua99/PandoraHelper/assets/32957221/97802d84-bcbb-4db8-8d54-8796d691ac33)
希望可以增加一个“每个月重置统计的使用量”的功能，和几个朋友拼plus，一个月结束了，比较方便看每个人的使用量。目前好像是只能按照每天重置。

**Comment by NPC-JIN** [comment]
我的解决方案是勾选那个每日重置限额，这样可以每天刷新统计里的次数

**Comment by hijos** [comment]
> 我的解决方案是勾选那个每日重置限额，这样可以每天刷新统计里的次数

这个我知道的，但是我想要以月为单位统计使用量，这样好和朋友分担费用
