### ISSUE TITLE
【数据库优化建议】删除了ChatGPT的plus帐号之后，在data.db中，还保留有共享帐号的信息，但是后台不可见。

### ISSUE THREAD

**Issue by joekleenubuntu** [nianhua99/PandoraHelper#92]
如题，如果可以优化一下就更好了，优化方案：
假设plus因为一些原因无法获取access token （过期或者帐号不可用的情况）可以把共享号一件转移到其他plus号中，这样就不用重复添加了。

![iUDr2boyQAaSpBu](https://s2.loli.net/2024/06/13/iUDr2boyQAaSpBu.png)

**Comment by nianhua99** [comment]
现在可以了，你把新的accesstoken编辑进去就行了
