### ISSUE TITLE
共享账号登录后白屏

### ISSUE THREAD

**Issue by zqyhimself** [nianhua99/PandoraHelper#93]
Docker 部署的，反代了主页，config 把 new 那个设置为反代后的域名了，共享账号登录就白屏
<img width="1106" alt="image" src="https://github.com/nianhua99/PandoraHelper/assets/123203214/94ebbe53-de44-4d34-a67f-0a201c17ab91">

**Comment by joekleenubuntu** [comment]
不要反代，看看是不是白屏？如果没有反代就白屏，那有可能是浏览器太老了，需要更新。
如果反代而导致白屏，那么就是反代设置错了，需要检查一下反代设置。
