### ISSUE TITLE
【bug反馈】删除（或者设置该帐号过期）共享uniquename帐号之后，该帐号的sharetoken 不会过期（依旧可以继续使用）

### ISSUE THREAD

**Issue by joekleenubuntu** [nianhua99/PandoraHelper#94]
如果共享的Unique Name帐号过期或者被删除之后，该共享帐号的share token 依旧可以使用。

测试可以复原。

解决方法：如果删除或者共享的列表帐号过期的话 吊销该 share token 。

**Comment by nianhua99** [comment]
没有这个问题，会吊销的
