### ISSUE TITLE
如果添加新账号的时候，输入账户密码即自动去始皇的token.oaifree.com服务获取rt或at就好了

### ISSUE THREAD

**Issue by 1951GIT** [nianhua99/PandoraHelper#98]
![image](https://github.com/user-attachments/assets/d08cfdf1-f539-473c-b4ef-72a10206d6b7)

![image](https://github.com/user-attachments/assets/32f83cbc-b958-4fbc-b2e6-6ca5e00f9e67)

**Comment by nianhua99** [comment]
这个没有提供 api
