### ISSUE TITLE
添加Claude账号后，无法登录

### ISSUE THREAD

**Issue by oneCatZz** [nianhua99/PandoraHelper#99]
添加了Claude的token后开启了分享，设置了账号密码后点击继续后无法跳转到始皇的Claude页面，我的ChatGPT和Claude的邮箱都是同一个，和这个有关系吗
![CleanShot 2024-08-03 at 22 29 39@2x](https://github.com/user-attachments/assets/e382d7f3-cf47-42ee-a916-378753c79729)

**Comment by nianhua99** [comment]
unique name重复没

**Comment by oneCatZz** [comment]
> unique name重复没

没有

**Comment by nianhua99** [comment]
配置文件里需要加一条，pandora.domain.claude，看readme

**Comment by oneCatZz** [comment]
老是忘记看，我的锅

**Comment by nianhua99** [comment]
> 老是忘记看，我的锅

其实是我的锅，因为readme是出了问题之后才更新的
